In [1]:
import torch

# Automatically select device
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU available via CUDA!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
    print("GPU available via Apple MPS backend!")
else:
    device = torch.device("cpu")
    print("No GPU available. Using CPU.")

# Example tensor on the selected device
x = torch.tensor([1.0, 2.0, 3.0], device=device)
print(f"Tensor device: {x.device}")

# Example: simple operation
y = x * 2
print("Result:", y)

GPU available via Apple MPS backend!
Tensor device: mps:0
Result: tensor([2., 4., 6.], device='mps:0')


## Creating a Tensor


In [12]:
# using empty
a = torch.empty(2,3)

In [13]:
# check type
type(a)

torch.Tensor

In [14]:
# using zeros
torch.zeros(4,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [15]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
# using rand , will be different everytime
torch.rand(2,3)

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])

In [42]:
# use of manual seed , will remain same everytime
torch.manual_seed(100)
print(torch.rand(2,3))


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
