In [1]:
import torch

# Automatically select device
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU available via CUDA!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
    print("GPU available via Apple MPS backend!")
else:
    device = torch.device("cpu")
    print("No GPU available. Using CPU.")

# Example tensor on the selected device
x = torch.tensor([1.0, 2.0, 3.0], device=device)
print(f"Tensor device: {x.device}")

# Example: simple operation
y = x * 2
print("Result:", y)

GPU available via Apple MPS backend!
Tensor device: mps:0
Result: tensor([2., 4., 6.], device='mps:0')


## Creating a Tensor


In [12]:
# using empty
a = torch.empty(2,3)

In [13]:
# check type
type(a)

torch.Tensor

In [14]:
# using zeros
torch.zeros(4,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [15]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
# using rand , will be different everytime
torch.rand(2,3)

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])

In [42]:
# use of manual seed , will remain same everytime
torch.manual_seed(100)
print(torch.rand(2,3))


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [46]:
# custom tensor
torch.tensor([[1, 2,3],[4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [50]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [55]:
b = torch.randn(2,3)
b.shape

torch.Size([2, 3])

In [56]:
torch.empty_like(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [57]:
torch.zeros_like(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [58]:
torch.ones_like(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [59]:
torch.rand_like(b)

tensor([[0.7775, 0.6179, 0.3379],
        [0.2170, 0.9454, 0.7116]])

## Tensor Data Types

In [61]:
# find data type
b.dtype

torch.float32

In [64]:
# assign data type
torch.tensor([0.2,0.2,0.3], dtype=torch.int32)

tensor([0, 0, 0], dtype=torch.int32)

In [66]:
torch.tensor([1,2,3], dtype=torch.float16)

tensor([1., 2., 3.], dtype=torch.float16)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


### 1. Scalar operation

In [67]:
x = torch.rand(2,2)
x

tensor([[0.1157, 0.6574],
        [0.3451, 0.0453]])

In [72]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0134, 0.4321],
        [0.1191, 0.0021]])