In [3]:
import torch

# Automatically select device
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU available via CUDA!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
    print("GPU available via Apple MPS backend!")
else:
    device = torch.device("cpu")
    print("No GPU available. Using CPU.")

# Example tensor on the selected device
x = torch.tensor([1.0, 2.0, 3.0], device=device)
print(f"Tensor device: {x.device}")

# Example: simple operation
y = x * 2
print("Result:", y)

GPU available via Apple MPS backend!
Tensor device: mps:0
Result: tensor([2., 4., 6.], device='mps:0')


## Creating a Tensor


In [4]:
# using empty
a = torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(4,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand , will be different everytime
torch.rand(2,3)

tensor([[0.5198, 0.4786, 0.6707],
        [0.7984, 0.3958, 0.3878]])

In [9]:
# use of manual seed , will remain same everytime
torch.manual_seed(100)
print(torch.rand(2,3))


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [10]:
# custom tensor
torch.tensor([[1, 2,3],[4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [12]:
b = torch.randn(2,3)
b.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
torch.zeros_like(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.ones_like(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
torch.rand_like(b)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

## Tensor Data Types

In [17]:
# find data type
b.dtype

torch.float32

In [18]:
# assign data type
torch.tensor([0.2,0.2,0.3], dtype=torch.int32)

tensor([0, 0, 0], dtype=torch.int32)

In [19]:
torch.tensor([1,2,3], dtype=torch.float16)

tensor([1., 2., 3.], dtype=torch.float16)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


### 1. Scalar operation

In [20]:
x = torch.rand(2,2)
x

tensor([[0.4440, 0.9478],
        [0.7445, 0.4892]])

In [21]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.1972, 0.8984],
        [0.5543, 0.2393]])

## 2. Element wise operation

In [22]:
a = torch.tensor([[7,8,9],[10,11,12]])
b = torch.tensor([[1,2,3],[4,5,6]])

print(a)
print(b)

tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [23]:
# add
a + b
# # sub
a - b
# # multiply
a * b
# # division
a / b
# # power
a ** b
# # mod
a % b

tensor([[0, 0, 0],
        [2, 1, 0]])

## 3. Reduction operation

In [24]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [27]:
# sum
sum = torch.sum(e)
print(sum)
# sum along columns
col_sum = torch.sum(e, dim=0)
print(col_sum)
# sum along rows
row_sum = torch.sum(e, dim=1)
print(row_sum)

tensor(24.)
tensor([ 8.,  0., 16.])
tensor([15.,  9.])


In [28]:
# mean
mean = torch.mean(e)
print(mean)
# mean along col
col_mean = torch.mean(e, dim=0)
print(col_mean)

tensor(4.)
tensor([4., 0., 8.])


In [30]:
# median
median = torch.median(e)
print(median)

tensor(0.)


In [32]:
# max and min
print(torch.max(e))
print(torch.min(e))

tensor(9.)
tensor(0.)


In [33]:
# product
torch.prod(e)

tensor(0.)

In [34]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [35]:
# variance
torch.var(e)

tensor(19.6000)

In [36]:
# argmax
torch.argmax(e)

tensor(5)

In [37]:
# argmin
torch.argmin(e)

tensor(1)

## 4. Matrix operations

In [38]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [39]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 87, 119],
        [ 65,  99]])

In [41]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [42]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [43]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [44]:
# determinant
torch.det(h)

tensor(-110.)

In [45]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

## 5. Comparison operations

In [47]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[3, 3, 5],
        [0, 6, 4]])
tensor([[0, 8, 4],
        [7, 2, 3]])


In [52]:
# greater than
print(i > j)
# less than
print(i < j)
# equal to
print(i == j)
# not equal to
print(i != j)
# greater than equal to

# less than equal to

tensor([[ True, False,  True],
        [False,  True,  True]])
tensor([[False,  True, False],
        [ True, False, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


## 6. Special functions

In [53]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[8., 5., 6.],
        [2., 9., 5.]])

In [54]:
# log
torch.log(k)

tensor([[2.0794, 1.6094, 1.7918],
        [0.6931, 2.1972, 1.6094]])

In [55]:
# exp
torch.exp(k)

tensor([[2.9810e+03, 1.4841e+02, 4.0343e+02],
        [7.3891e+00, 8.1031e+03, 1.4841e+02]])

In [56]:
# sqrt
torch.sqrt(k)

tensor([[2.8284, 2.2361, 2.4495],
        [1.4142, 3.0000, 2.2361]])

In [57]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9997, 0.9933, 0.9975],
        [0.8808, 0.9999, 0.9933]])

In [58]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9975, 0.0180, 0.7311],
        [0.0025, 0.9820, 0.2689]])

In [59]:
# relu
torch.relu(k)

tensor([[8., 5., 6.],
        [2., 9., 5.]])

## 7 Inplace Operations

In [60]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])
tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])


In [61]:
m.add_(n)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [62]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [63]:
n

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [64]:
torch.relu(m)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [65]:
m.relu_()

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [66]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])